server:
  port: 7000
spring:
  cloud:
    gateway:
      routes:
      - id: serv-vuelos
        uri: lb://servicio-vuelos
        predicates: 
          - Path=/svuelos/**
        filters:
        - RewritePath=/svuelos/*, /
eureka:
  client:
    service-url:
      defaultZone: http://http://172.20.160.190:8761/eureka
